# Python Numpy machine learning

In [1]:
import numpy as np

### Constructeurs

In [9]:
np.array([1, 2, 3])  # construction d'un array
np.array([1, 2, 3], dtype=float)  # construction d'un array de float
np.array([[1, 2, 3], [4, 5, 6]])  # construction d'un array 2D
np.zeros((3, 2))  # construction d'un array de 0
np.ones((3, 2))  # construction d'un array de 1
np.full((3, 2), 4)  # construction d'un array de 4
np.random.rand(3, 2)  # construction d'un array de nombres aléatoires
np.random.randn(3, 2)  # construction d'un array de nombres aléatoires
np.random.normal(0, 1, (3, 2))  # construction d'un array de nombres aléatoires
np.random.uniform(0, 1, (3, 2))  # construction d'un array de nombres aléatoires
np.eye(3)  # construction d'un array identité
np.linspace(0, 1, 5) # 5 points entre 0 et 1
np.arange(0, 1, 0.1) # de 0 à 1 par pas de 0.1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### Affichage de divers Arguments de ndarray
https://numpy.org/devdocs/reference/generated/numpy.ndarray.html

In [10]:
firstArray = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
print("firstArray :\n", firstArray)
print("firstArray.shape :", firstArray.shape)
print("firstArray.size :", firstArray.size)
print("firstArray.ndim :", firstArray.ndim)
print("firstArray.dtype :", firstArray.dtype)
print("firstArray.itemsize :", firstArray.itemsize)
print("firstArray.nbytes :", firstArray.nbytes)

firstArray :
 [[1 2 3]
 [4 5 6]]
firstArray.shape : (2, 3)
firstArray.size : 6
firstArray.ndim : 2
firstArray.dtype : int64
firstArray.itemsize : 8
firstArray.nbytes : 48


### Data Type - dtype
https://numpy.org/devdocs/reference/arrays.dtypes.html#arrays-dtypes-constructing

In [14]:
np.int_
np.intc
np.intp
np.int8
np.int16
np.int32
np.int64
np.uint8
np.uint16
np.uint32
np.uint64
np.float16
np.float32
np.float64
np.complex64
np.complex128
np.complex256
np.bool_
np.object_
np.bytes_
np.datetime64
np.timedelta64

numpy.timedelta64

### Methode de manipulation

In [23]:
a = np.zeros((3, 2))
b = np.ones((3, 2))
print("np.vstack((a,b)) or np.concatenate((a,b), axis=0) :\n", np.concatenate((a,b), axis=0))
print("np.hstack((a,b)) or np.concatenate((a,b), axis=1) :\n", np.concatenate((a,b), axis=1))

np.vstack((a,b)) or np.concatenate((a,b), axis=0) :
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
np.hstack((a,b)) or np.concatenate((a,b), axis=1) :
 [[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]


In [25]:
D = np.concatenate((a,b), axis=0)
print("D - D.shape=", D.shape, "D.size=", D.size, "\n", D)
D = D.reshape(3, 4)
print("D.reshape(3, 4) - D.shape=", D.shape, "D.size=", D.size, "\n", D)


D - D.shape= (6, 2) D.size= 12 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
D.reshape(3, 4) - D.shape= (3, 4) D.size= 12 
 [[0. 0. 0. 0.]
 [0. 0. 1. 1.]
 [1. 1. 1. 1.]]


In [30]:
D = D.squeeze()
D = D.reshape(D.shape[0], 1)
print("D.squeeze() - D.shape=", D.shape, "D.size=", D.size, "\n", D)
E = D.flatten()
print("E.flatten() - E.shape=", E.shape, "E.size=", E.size, "\n", E)
F = D.ravel()
print("F.ravel() - F.shape=", F.shape, "F.size=", F.size, "\n", F)

G = np.array([[1, 2, 3], [4, 5, 6]])
print("G :\n", G)
G.T
print("G.T :\n", G.T)


D.squeeze() - D.shape= (12, 1) D.size= 12 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
E.flatten() - E.shape= (12,) E.size= 12 
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
F.ravel() - F.shape= (12,) F.size= 12 
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
G :
 [[1 2 3]
 [4 5 6]]
G.T :
 [[1 4]
 [2 5]
 [3 6]]
