# Python Numpy indexing slicing masking  

In [3]:
import numpy as np

### Indexing

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print ("A[2, 2] = A[2][2] =", A[2, 2])
print ("A[1] = A[1][:] =", A[1])
print (f"A[0:3,1:3] = A[:,-2:] = \n", A[:, -2:])

A[2, 2] = A[2][2] = 9
A[1] = A[1][:] = [4 5 6]
A[0:3,1:3] = A[:,-2:] = 
 [[2 3]
 [5 6]
 [8 9]]


In [17]:
B = np.zeros((4, 4))
B[1:3, 1:3] = 1
print("B :\n", B)

B :
 [[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [18]:
C = np.zeros((5, 5))
C[::2, ::2] = 1
print("C :\n", C)

C :
 [[1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1.]]


### Boolean indexing / masking / filtering

In [28]:
D = np.random.randint(0, 10, (5, 5))
print("D :\n", D)
mask = D <= 5
print("mask :\n", mask)
D[mask] = 0
print("D[mask]=0 :\n", D)
D[(D==0) | (D==9)] = 3
print("D[(D==0) | (D==1)] = 10 :\n", D)

D :
 [[5 3 4 0 9]
 [9 4 5 0 7]
 [6 1 0 3 8]
 [6 0 9 7 6]
 [8 3 2 3 3]]
mask :
 [[ True  True  True  True False]
 [False  True  True  True False]
 [False  True  True  True False]
 [False  True False False False]
 [False  True  True  True  True]]
D[mask]=0 :
 [[0 0 0 0 9]
 [9 0 0 0 7]
 [6 0 0 0 8]
 [6 0 9 7 6]
 [8 0 0 0 0]]
D[(D==0) | (D==1)] = 10 :
 [[3 3 3 3 3]
 [3 3 3 3 7]
 [6 3 3 3 8]
 [6 3 3 7 6]
 [8 3 3 3 3]]


In [35]:
A = np.random.randint(0, 10, (5, 5))
print("A :\n", A)
print("A[(A>2) | (A<8)] =", A[(A>2) & (A<8)])

A :
 [[5 5 8 3 8]
 [0 1 0 7 3]
 [8 7 1 4 6]
 [6 5 8 6 8]
 [6 4 5 4 3]]
A[(A>2) | (A<8)] = [5 5 3 7 3 7 4 6 6 5 6 6 4 5 4 3]
