# Numpy Methodes : Math, stat, et autres....
https://docs.scipy.org/doc/numpy-1.10.1/reference/routines.html  

In [33]:
import numpy as np

In [ ]:
A = np.random.randint(0, 10, (2, 3))
A

array([[2, 1, 0],
       [0, 4, 4]])

In [ ]:
print("A.sum() =", A.sum())  # somme des éléments
print("A.sum(axis=0) = A.sum(0) =", A.sum(axis=0)) # somme des colonnes
print("A.sum(axis=1) = A.sum(1) =", A.sum(axis=1)) # somme des lignes
print("A.cumsum() =", A.cumsum()) # somme cumulée
print("A.prod() =", A.prod()) # produit des éléments
print("A.cumprod() =", A.cumprod()) # produit cumulé

A.sum() = 11
A.sum(axis=0) = A.sum(0) = [2 5 4]
A.sum(axis=1) = A.sum(1) = [3 8]
A.cumsum() = [ 2  3  3  3  7 11]
A.prod() = 0
A.cumprod() = [2 2 0 0 0 0]


In [ ]:
A = np.random.randint(0, 10, (3, 3))
print("A :\n", A)
print("A.min() =", A.min()) # minimum
print("A.max() =", A.max()) # maximum
print("A.argmin(axis=0) =", A.argmin(axis=0), "A.argmin(axis=1) =", A.argmin(axis=1)) # indice du minimum
print("A.argmax(axis=0) =", A.argmax(axis=0), "A.argmax(axis=1) =", A.argmax(axis=1)) # indice du maximum



A :
 [[7 7 3]
 [7 4 2]
 [1 5 7]]
A.min() = 1
A.max() = 7
A.argmin(axis=0) = [2 1 1] A.argmin(axis=1) = [2 2 0]
A.argmax(axis=0) = [0 0 2] A.argmax(axis=1) = [0 0 2]


In [ ]:
A = np.random.randint(0, 10, (3, 3))
print("A :\n", A)
B = A.copy()
B.sort(axis=0) # tri par colonne
print("B.sort(axis=0) :\n", B)
B.sort(axis=1) # tri par ligne
print("B.sort(axis=1) :\n", B)
C = A.copy()
C.argsort(axis=0) # indice des éléments triés par colonne
print("C.argsort(axis=0) :\n", C)
C = C.argsort(axis=1) # indice des éléments triés par ligne
print("C.argsort(axis=1) :\n", C)

A :
 [[0 4 7]
 [4 9 3]
 [1 2 4]]
B.sort(axis=0) :
 [[0 2 3]
 [1 4 4]
 [4 9 7]]
B.sort(axis=1) :
 [[0 2 3]
 [1 4 4]
 [4 7 9]]
C.argsort(axis=0) :
 [[0 4 7]
 [4 9 3]
 [1 2 4]]
C.argsort(axis=1) :
 [[0 1 2]
 [2 0 1]
 [0 1 2]]


### Numpy Mathemaical functions
https://docs.scipy.org/doc/numpy-1.10.1/reference/routines.math.html

In [ ]:
np.sin(A)
np.log(A)
np.exp(A)
# ...

/var/folders/4y/lgszfx9552xg0mrhrk5x840h0000gn/T/ipykernel_2494/3182848200.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(A)


array([[1.00000000e+00, 5.45981500e+01, 1.09663316e+03],
       [5.45981500e+01, 8.10308393e+03, 2.00855369e+01],
       [2.71828183e+00, 7.38905610e+00, 5.45981500e+01]])

### Numpy Statistics functions
https://docs.scipy.org/doc/numpy-1.10.1/reference/routines.statistics.html

In [52]:
print (A)
print ("A.mean() =",A.mean()) # moyenne
print ("A.mean(axis=0) =",A.mean(axis=0)) # moyenne des colonnes
print ("A.mean(axis=1) =",A.mean(axis=1)) # moyenne des lignes

[[0 4 7]
 [4 9 3]
 [1 2 4]]
A.mean() = 3.7777777777777777
A.mean(axis=0) = [1.66666667 5.         4.66666667]
A.mean(axis=1) = [3.66666667 5.33333333 2.33333333]


In [53]:
print ("A.var() =",A.var()) # variance

A.var() = 7.061728395061728


In [54]:
print ("A.std() =",A.std()) # écart-type

A.std() = 2.657391276244755


In [57]:
print (A)
print ("np.corrcoef(A) =\n",np.corrcoef(A)) # coefficient de corrélation
print ("np.corrcoef(A)[0,1] =",np.corrcoef(A)[0,1]) # coefficient de corrélation

[[0 4 7]
 [4 9 3]
 [1 2 4]]
np.corrcoef(A) =
 [[ 1.         -0.07381732  0.96312314]
 [-0.07381732  1.         -0.33942212]
 [ 0.96312314 -0.33942212  1.        ]]
np.corrcoef(A)[0,1] = -0.07381732441968657


In [61]:
print("np.unique(A) =",np.unique(A)) # valeurs uniques
print("np.unique(A, return_counts=True) =",np.unique(A, return_counts=True)) # valeurs uniques et leurs counts
print("np.unique(A, return_index=True) =",np.unique(A, return_index=True)) # valeurs uniques et leurs indices
print("np.unique(A, return_inverse=True) =",np.unique(A, return_inverse=True)) # valeurs uniques et leurs indices inversés
# tri par ordre de fréquence (argsort retourne les indices triés pour que les valeurs soient dans l'ordre croissant)
values, counts = np.unique(A, return_counts=True)
print("values[counts.argsort()] =",values[counts.argsort()]) # valeurs uniques triées par ordre de fréquence
# affichage des valeurs uniques triées par ordre de fréquence
for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f"valeur : {i} - apparait : {j} fois")

np.unique(A) = [0 1 2 3 4 7 9]
np.unique(A, return_counts=True) = (array([0, 1, 2, 3, 4, 7, 9]), array([1, 1, 1, 1, 3, 1, 1]))
np.unique(A, return_index=True) = (array([0, 1, 2, 3, 4, 7, 9]), array([0, 6, 7, 5, 1, 2, 4]))
np.unique(A, return_inverse=True) = (array([0, 1, 2, 3, 4, 7, 9]), array([[0, 4, 5],
       [4, 6, 3],
       [1, 2, 4]]))
values[counts.argsort()] = [0 1 2 3 7 9 4]
valeur : 0 - apparait : 1 fois
valeur : 1 - apparait : 1 fois
valeur : 2 - apparait : 1 fois
valeur : 3 - apparait : 1 fois
valeur : 7 - apparait : 1 fois
valeur : 9 - apparait : 1 fois
valeur : 4 - apparait : 3 fois


In [71]:
# nan functions for missing values
B = (A.copy()).astype(np.float64)
B[1,1] = np.nan
B[2,2] = np.nan
np.nansum(B) # somme des éléments, en ignorant les NaNs
np.nanprod(B) # produit des éléments, en ignorant les NaNs
np.nanmean(B) # moyenne des éléments, en ignorant les NaNs
np.nanmedian(B) # médiane des éléments, en ignorant les NaNs
np.nanstd(B) # écart-type des éléments, en ignorant les NaNs
np.nanvar(B) # variance des éléments, en ignorant les NaNs

np.isnan(B) # renvoie un tableau de booléens, True si l'élément est NaN, False sinon
np.isnan(B).sum() # nombre de NaNs dans B
np.isnan(B).sum()/B.size # pourcentage de NaNs dans B

B[np.isnan(B)] = 0 # remplacement des NaNs par 0

### Numpy Algebre lineaire
https://docs.scipy.org/doc/numpy-1.10.1/reference/routines.linalg.html

In [ ]:
A = np.ones(2,3)
B = np.ones(3,2)

A.T # transposition
A.dot(B) # produit matriciel

A = np.random.randint(1, 10, (3, 3))
np.linalg.det(A) # déterminant
np.linalg.inv(A) # inverse

np.linalg.eig(A) # valeurs propres et vecteurs propres
np.linalg.svd(A) # décomposition en valeurs singulières
np.linalg.qr(A) # décomposition QR

### Exercice

In [73]:
np.random.seed(0)
A = np.random.randint(0, 100, (10, 5))
A

# normalisation/standardisation (z-score)
mean = A.mean(axis=0) # moyenne des colonnes
std = A.std(axis=0) # écart-type des colonnes
A_std = (A - mean) / std # standardisation

print(A)
print("standardisation (z-score) par colone")
print(A_std)

[[44 47 64 67 67]
 [ 9 83 21 36 87]
 [70 88 88 12 58]
 [65 39 87 46 88]
 [81 37 25 77 72]
 [ 9 20 80 69 79]
 [47 64 82 99 88]
 [49 29 19 19 14]
 [39 32 65  9 57]
 [32 31 74 23 35]]
standardisation (z-score) par colone
[[-0.02206157  0.          0.13173823  0.72539252  0.10755798]
 [-1.56637126  1.61579632 -1.48676006 -0.33034307  0.96802178]
 [ 1.12513992  1.84021247  1.03508612 -1.14768676 -0.27965074]
 [ 0.90452425 -0.35906585  0.99744662  0.0102168   1.01104497]
 [ 1.6104944  -0.44883231 -1.33620208  1.0659524   0.32267393]
 [-1.56637126 -1.21184724  0.73397016  0.7935045   0.62383626]
 [ 0.11030784  0.76301493  0.80924915  1.81518411  1.01104497]
 [ 0.1985541  -0.80789816 -1.56203905 -0.90929485 -2.17267111]
 [-0.24267724 -0.67324847  0.16937773 -1.24985473 -0.32267393]
 [-0.55153918 -0.7181317   0.50813319 -0.77307091 -1.26918412]]
