# Python Numpy Broadcasting

In [1]:
import numpy as np

### Broadcasting
1. c est un nombre donc un scalaire (1,1,1,...)
2. les dimensions sont les mêmes

In [2]:
np.random.seed(0)
A = np.random.randint(0, 10, (2, 3))
print("1. A + 1 =\n",A + 1)
B = np.ones((2, 3))
print("2. A + B =\n",A + B) # additionne si les dimensions sont les mêmes 

1. A + 1 =
 [[ 6  1  4]
 [ 4  8 10]]
2. A + B =
 [[ 6.  1.  4.]
 [ 4.  8. 10.]]


3. une dimension est 1 et l'autre est commune (1,3) ou (2,1)

In [3]:
C = np.ones((2, 1))
print(C)
print("3. A + C =\n", A + C) # C est ajouté à chaque colonne de A
D = np.ones((1, 3))
print(D)
print("3. A + D =\n", A + D) # D est ajouté à chaque ligne de A
# pour verifier


[[1.]
 [1.]]
3. A + C =
 [[ 6.  1.  4.]
 [ 4.  8. 10.]]
[[1. 1. 1.]]
3. A + D =
 [[ 6.  1.  4.]
 [ 4.  8. 10.]]


4. si les dimention sont transopsee avec 1

In [4]:
A = np.array([[1, 2, 3]])
B = np.array([[4], [5], [6]])
print("4. A + B =\n",A + B)

4. A + B =
 [[5 6 7]
 [6 7 8]
 [7 8 9]]
